### ISSUE TITLE
how to check translation file existence ?

### ISSUE THREAD

**Issue by aniinprni** [i18next/i18next-node-fs-backend#10]
Hi I am using `Backend` module to load translations. My requirement is i need to check local translation files and if not exists i need to create one file and load data to it from mongodb. Is it possible to achieve it ? And Also please tell me Is there any facility that `i18next` will read translations from redis ?

Thanks in Advance

**Comment by jamuhl** [comment]
1) if file is not existing there are two options:

a) we emit generally a failedLoading event here: https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L91

b) you create a own fs backend that checks for file exists and on not existing you load data from mongo


2) redis backend

That does not yet exist. Sorry. Feel free to create one and share it with community.

**Comment by aniinprni** [comment]
Thanks Jan Mühlemann

**Comment by jamuhl** [comment]
http://i18next.com/docs/api/#on-failedloading was added in i18next v2.0.17
