### ISSUE TITLE
Undefined key if gettext (flat) format is used, hence, no extraction of missing string and server error

### ISSUE THREAD

**Issue by thaerlabs** [i18next/i18next-node-fs-backend#2]
on https://github.com/i18next/i18next-node-fs-backend/blob/master/src/index.js#L69

If the **key** doesn't have a `.`, results in an `undefined` key. I've worked around this by doing this.

```javascript
69:  const _key = key.split['.'] || key;
70:  utils.setPath(resources, _key, fallbackValue); // TODO: use this.coreOptions.keySeparator;
```

I tried to fork the repo and add it by myself but it's missing dependencies and browserify isn't there.. so please can you fix this?

**NOTE:** I'm integrating i18next in an isomorphic app using redux/react, so the server is needed to extract the missing strings and add the to the template. if you have better solutions for this I'm open to anything :D

**Comment by jamuhl** [comment]
hm...if key is a string it will result in [str]

"str".spit('.') --> [str]

or do i miss something? is the key itself undefined?

**Comment by pgom** [comment]
@jamuhl, The problem here is with split function `.split['.']` doesn't exist so it should be changed to `.split('.')`

**Comment by jamuhl** [comment]
haha...lol...blind me ;)...will be fixed asap

**Comment by thaerlabs** [comment]
@jamuhl the key is defined.
But it's weird because when I use it as `i18next.t('some.missing.key')` I will get the output
```
{
  "some": {
    "missing": {
      "key" : "some.missing.key"
    }
  }
}
```

And I get an error when used as `i18next.t('mystring')` in the `indexOf` call inside the `lib/utils.js` in the `setPath` function.

@pgom your point is legit ;)

**Comment by jamuhl** [comment]
try v0.0.5 just published on npm...should fix this

**Comment by thaerlabs** [comment]
@jamuhl thanks, will test it soon and get back to you

**Comment by thaerlabs** [comment]
@jamuhl 100% working. :D
