### ISSUE TITLE
Support yaml extension

### ISSUE THREAD

**Issue by qraynaud** [i18next/i18next-node-fs-backend#208]
Hi,

It took me some time to figure out that the parser error occuring on my yaml file was due to the wrong parser being used.

I'm using the `.yaml` extension (that is recommanded by the YAML maintainers and is more explicit, at least to me) and it's failing because it's using the JSON parser on it.

I suggest the followings:
- fail on unrecognised extensions rather than defaulting to JSON parser
- accept the `.yaml` file extension

Another option is to use the YAML parser for JSON files too (since YAML is a superset of JSON) but I'm not sure it is a bright idea ^^. And it is not compatible with JSON 5 sadly.

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-node-fs-backend/blob/master/src/index.js#L27

yaml is supported for extension yml (not sure...yaml support wasn't added by myself)...so we could just extend that to support `.yaml` too

**Comment by jamuhl** [comment]
could you test if the parser would correctly parse your file by changing the extension temporary to `.yml`?

**Comment by qraynaud** [comment]
@jamuhl : I should have stated that I tried and that it works. It's just .yml is not "the correct" extension for yaml files. A lot of people use it but it is a mistake. The "official" extension for YAML files is .yaml.

**Comment by jamuhl** [comment]
should be fixed in 0.1.3

**Comment by qraynaud** [comment]
Thanks @jamuhl
