### ISSUE TITLE
Error: Cannot resolve module 'fs'

### ISSUE THREAD

**Issue by hshercha** [i18next/i18next-node-fs-backend#215]
```
ERROR in ./~/i18next-node-fs-backend/lib/index.js
Module not found: Error: Cannot resolve module 'fs' in projects/helloWorld/node_modules/i18next-node-fs-backend/lib
 @ ./~/i18next-node-fs-backend/lib/index.js 21:10-23
```

Webpack threw this error when I tried to use this package. After scavenging around the web, I found few others who mentioned to add this workaround in the webpack config:
```
node : {
        fs : empty
    }
```
Could someone explain why this works? To meet it seems like it's just mitigating the issue by making 'fs' to an empty module, which is bad if there are other packages that has the 'fs' dependency. However, it does load the translation files. So maybe I am no completely understanding what the empty value does to the fs attribute?

**Comment by jamuhl** [comment]
why you want to bundle that with webpack - that backend is for node.js - use the xhr backend for browser...??!?

**Comment by hshercha** [comment]
Sorry I am new to this. I was under the assumption that by using the node-backend it was bundling the translation files from the file system instead of making the http request.

**Comment by jamuhl** [comment]
http://i18next.com/docs/ecosystem/#utils -> webpack i18next-resource-store-loader

https://github.com/atroo/i18next-resource-store-loader

**Comment by hshercha** [comment]
Thanks!
