### ISSUE TITLE
Problem setting everything up in Nodejs/Electron

### ISSUE THREAD

**Issue by Jacky2611** [i18next/i18next-node-fs-backend#217]
OK, so I have slight problems setting everything up using nodejs with electron.
Everything works fine when I give i18n all the language mapping directly in the init method. However, if i try something like this in my renderer:

```
i18next
    .use(Backend)
    .init({
      backend: {
          // path where resources get loaded from
          loadPath: '/locales/{{lng}}/{{ns}}.json',

          // path to post missing resources
          addPath: '/locales/{{lng}}/{{ns}}.missing.json',

          // jsonIndent to use when storing json files
          jsonIndent: 2
      },
      lng: 'en' // upgrade to language-detector/let user decide
    }, function(err, t) {
      var test =i18next.t('key');
      console.log("so far so good  "+ test);
    });
```

It stops working. I neither get a error message nor is a folder for missing resources created anywhere. It doesn't find a en.json file either if I provide it. Does anyone know what I am doing wrong?

And could someone tell me for what exactly ns stands? I tried googeling it but nothing was clear about it. I am assuming I can simply remove it and use something like .../{{lng}}.json but I would still like to know for what it is good. As far as I understand it I can use it to split my translation file into multiple parts.

**Comment by jamuhl** [comment]
Namespaces can be used to structure your translations into multiple files.

using namespaces: http://i18next.com/translate/namespace/
some infos why to use namespaces: http://locize.com/namespaces.html

You issue:

turn on `debug: true` on init...i'm rather sure the loadPath is wrong or can't read from...setting debug true should show you that info.

**Comment by Jacky2611** [comment]
Turns out that I might have forgotten to use something like path.join(__dirname, "../localize/..."). 
Thank you for pointing out the debug option @jamuhl , it's been extremely helpful for me.

Only thing that I haven't gotten working yet is addPath. I did set saveMissing to true in the init options but I am somewhat confused since apparently i18next-node-fs-backend has no endpoint for missingKeyHandler (which should be called from i18n). So why is there a addPath option?

**Comment by jamuhl** [comment]
hmm...saving missing should work:

https://github.com/i18next/i18next-node-fs-backend/blob/master/src/index.js#L86

gets called on missing https://github.com/i18next/i18next/blob/master/src/Translator.js#L146 via backend https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L233

might be missing write permission...?!?

could you log https://github.com/i18next/i18next-node-fs-backend/blob/master/lib/index.js#L183 if there is an err (just modify that file in your node_modules folder)

**Comment by Jacky2611** [comment]
I get the following error::
ENOENT: no such file or directory, open 'D:\Development\Node.js\StoryWriter\locales\dev\editor.missing.json'

**Comment by jamuhl** [comment]
would need to check if path exists...will look if i could add that for next version.

great it works now

**Comment by Jacky2611** [comment]
Yeah, would be great if you could add it.
And thanks for all the help!
