### ISSUE TITLE
Dependency not found

### ISSUE THREAD

**Issue by epartipilo** [i18next/i18next-node-fs-backend#218]
Hello, I get this:

```
This dependency was not found:

* fs in ./~/i18next-node-fs-backend/lib/index.js
```

code:
```
import Backend from 'i18next-node-fs-backend'

...
backend: {
        loadPath: '/translations/{{lng}}/{{ns}}.json'
    }

i18next
    .use(Backend)
```

**Comment by jamuhl** [comment]
fs is part of node.js...do you use some different environment? or babel-core? something must be different to the "regular" case...

**Comment by epartipilo** [comment]
Thanks for the answer,
I use Node, in fact I have an script that uses this
```const fs = require('fs')```

so I suppose your library must work.

I use Babel and Webpack. I'm developing a Nuxt.js app using the recipe they propose.

Thanks!

**Comment by jamuhl** [comment]
try `const Backend = require('i18next-node-fs-backend');` might be related to import...but idk.

**Comment by epartipilo** [comment]
Sorry, when working with Nuxt I have to be aware of front-end and back-end, seems the error jumped on the front-end cycle obviously.
Now I'm not getting the error, lets see if it works.

Thanks!
