### ISSUE TITLE
'en-US' file not found when 'en' file is there ? 

### ISSUE THREAD

**Issue by poppein** [i18next/i18next-node-fs-backend#219]
Hi,

I'm having an issue when running my Electron app on Mac with i18n. It basically tries to load the 'en-US' file and raises an error saying that the file is not there (which is true) but it stops there and does not look for the 'en' file, which exists. 

I'm initializing i18n like this : 
```
const languageDetector = require('i18next-electron-language-detector');
const backend = require('i18next-node-fs-backend');

18n
    .use(languageDetector)
    .use(backend)
    .init(
        {
            preload: ['en', 'fr'],
            fallbackLng: 'en',
            ns: ['common'],
            defaultNS: 'common',
            debug: false,
            backend: {
                loadPath: path.join(__dirname, 'locales/{{lng}}/{{ns}}.json')
            },
            react: {
                wait: true
            }
        }, callback)
    ;
```
I have a "en" and a "fr" folder. Isn't the module supposed to fallback to "en" if it does not find "en-US" ?

**Comment by jamuhl** [comment]
should do so - at least does so for node.js. Never tried personally on electron.

In your case it should load `en` and `fr` (en as fallback and both as preload).

Do you get any error msg if setting `debug=true`?!?

**Comment by poppein** [comment]
I just tried a simple Node.js example and it doesn't seem to work either.

```js
const i18n = require('i18next');
const backend = require('i18next-node-fs-backend');
const path = require('path');
const languageDetector = require('./languageDetector');

i18n
.use(languageDetector)
.use(backend)
.init(
    {
        fallbackLng: 'en',
        ns: ['common'],
        defaultNS: 'common',
        debug: true,
        backend: {
            loadPath: path.join(__dirname, 'locales/{{lng}}/{{ns}}.json')
        }
    }, (err, t) => {
        if(err)
            throw new Error(err);
        console.log(t('testString'));
    });
```

I created the following language detector to force 'en-US' : 

```js
module.exports = {
  'init' : Function.prototype,
  'type' : 'languageDetector',
  'detect' : () => 'en-US',
  'cacheUserLanguage' : Function.prototype
};
```
And used the following json file for translations, located in /locales/en/common.json 👍 
```json
{
    "testString": "This is a string in english"
}
```
I end up with the following error :

> Error: Error: ENOENT: no such file or directory, open 'C:\_DevRootGit\Demo\i18ntest\locales\en-US\common.json'

The debug log shows the following : 

> i18next::backendConnector: loading namespace common for language en-US failed { Error: ENOENT: no such file or directory, open 'C:\_DevRootGit\Demo\i18ntest\locales\en-US\common.json'
>     at Error (native)
>   errno: -4058,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: 'C:\\_DevRootGit\\Demo\\i18ntest\\locales\\en-US\\common.json' }
> i18next::backendConnector: loaded namespace common for language en { testString: 'This is a string in english' }
> i18next: languageChanged en-US
> i18next: initialized { debug: true,
>   initImmediate: true,
>   ns: [ 'common' ],
>   defaultNS: 'common',
>   fallbackLng: [ 'en' ],
>   fallbackNS: false,
>   whitelist: false,
>   nonExplicitWhitelist: false,
>   load: 'all',
>   preload: false,
>   simplifyPluralSuffix: true,
>   keySeparator: '.',
>   nsSeparator: ':',
>   pluralSeparator: '_',
>   contextSeparator: '_',
>   saveMissing: false,
>   saveMissingTo: 'fallback',
>   missingKeyHandler: false,
>   postProcess: false,
>   returnNull: true,
>   returnEmptyString: true,
>   returnObjects: false,
>   joinArrays: false,
>   returnedObjectHandler: [Function: returnedObjectHandler],
>   parseMissingKeyHandler: false,
>   appendNamespaceToMissingKey: false,
>   appendNamespaceToCIMode: false,
>   overloadTranslationOptionHandler: [Function: handle],
>   interpolation:
>    { escapeValue: true,
>      format: [Function: format],
>      prefix: '{{',
>      suffix: '}}',
>      formatSeparator: ',',
>      unescapePrefix: '-',
>      nestingPrefix: '$t(',
>      nestingSuffix: ')',
>      maxReplaces: 1000 },
>   backend: { loadPath: 'C:\\_DevRootGit\\Demo\\i18ntest\\locales\\{{lng}}\\{{ns}}.json' } }

**Comment by poppein** [comment]
Ok i found the problem. I stated that a callback with an "err" parameter defined meant that i18n initialization failed which is partially true. The "err" parameter will actually contain the message indicating that the "en-US" file was not found, but it doesn't mean that it didn't find the "en" file. If you just ignore the error and move on translating something, you get the translation from the "en" file.  So it works indeed, but the fact that an error is provided even if you actually loaded something is kinda confusing :)

**Comment by jamuhl** [comment]
ah ok....i really thought it did not load `en` at all. Sorry for misunderstanding that.

you can set `load: 'languageOnly'` on init -> that way it does only load languages without region consideration.

**Comment by Cinamonas** [comment]
@jamuhl, this is a valid issue. Following this specific example, if I set `load: 'all'`, it means that I want the backend to try loading `en-US` and fall back to `en` only if the former is not available. Trying to load `en-US` should not result in an exception. And now it does.

**Comment by jamuhl** [comment]
@Cinamonas result in an exception -> you mean the network error in the browsers console...that is no exception that is regular behaviour of a network call returning statuscode 400!

It load both -> as en acts as a fallback in each case...in en-US you can just override the translations that eg. differ from en (lets assume you use en-GB as base for en - in the other case you even can remove en-US leaving that empty).

If needing the other behaviour you might need to create some own backend doing so.

**Comment by Cinamonas** [comment]
But we’re talking about the Node backend here – not the browser. So the exception happens on the server-side. In my specific case, we’re doing server-side rendering, where namespaces are being preloaded, but when attempting to load `en-US` (which doesn’t exist, but `en` does), an exception is thrown _on server-side_ that the file cannot be found. My current workaround is to catch `ENOENT: no such file or directory` in such case, but ideally, this i18next backend should handle it.

**Comment by jamuhl** [comment]
but it's just a warning...it does not crash your server - it just says you're user requested en-US and you only provide en. If you do not like to provide locales (lng-region) just set load option to `languageOnly` or `currentOnly` or set the whitelist like needed.

**Comment by jamuhl** [comment]
or set debug: false - and ignore it ;)

**Comment by jamuhl** [comment]
i'm not sure...but fs.readfile should not throw.

**Comment by jamuhl** [comment]
if so...creating a PR with a try-catch around the read should help
