### ISSUE TITLE
Doesn't seem to find namespaced translation files

### ISSUE THREAD

**Issue by magnuspaaske** [i18next/i18next-node-fs-backend#221]
For a project I'm making I'm looking to make different translation files for different name spaces. The file structure should be something like this:

```
locales
-> en
--> home.json
--> about_us.json
-> es
--> home.json
--> about_us.json
```
etc

However, it seems to only look for files named `translation.json`, and if the key is not in that file the key gets added to `translation.missing.json`.

I'm loading the translations as such:
```
i18next
    .use(i18nextBackend)
    .use(i18nextMiddleware.LanguageDetector)
    .init({
        backend: {
            loadPath: __dirname + '/locales/{{lng}}/{{ns}}.json',
            addPath: __dirname + '/locales/{{lng}}/{{ns}}.missing.json',
        },
        detection: {
            order: ['querystring', 'cookie'],
            caches: ['cookie'],
        },
        fallbackLng: 'en',
        // preload: ['en', 'es'],
        saveMissing: true
    })
```

Is there something I'm missing or how should I add namespaced translation files?

/Magnus

**Comment by jamuhl** [comment]
Sure you missing something - translation is the default namespace set, add additional namespaces, set default on init like: https://www.i18next.com/principles/namespaces#sample

**Comment by magnuspaaske** [comment]
Okay, that worked when I used a colon to denote the value I'm going for (so use `home:title` rather than `home.title`)

**Comment by magnuspaaske** [comment]
So my issue should be fixed even if the documentation does seem a bit lacking on this

**Comment by jamuhl** [comment]
guess it's in the docs under ESSENTIALS: https://www.i18next.com/translation-function/essentials#accessing-keys-in-different-namespaces

**Comment by jamuhl** [comment]
closing this for now...feel free to reopen if needed
