### ISSUE TITLE
Support keySeperator: false

### ISSUE THREAD

**Issue by daveparslow** [i18next/i18next-node-fs-backend#222]
in index.js

The following code doesn't support the option keySeperator: false which will cause it to use '.' instead

missings.forEach((missing) => {
          utils.setPath(resources, missing.key.split(this.coreOptions.keySeparator || '.'), missing.fallbackValue);
});

**Comment by jamuhl** [comment]
should be supported in i18next-node-fs-backend@1.1.0

**Comment by daveparslow** [comment]
That was quick 💯 Confirmed that keySeperator: false is working in 1.1.0
