### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by lenghia241** [i18next/i18next-node-fs-backend#228]
have this error when trying to import Back end from the dependency

`
./node_modules/i18next-sync-fs-backend/lib/index.js
Critical dependency: the request of a dependency is an expression

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
`
Full i18next init:

`import i18n from "i18next";

import Config from "./data/parameters.js";

import locales from "sas-translations";

const Backend = require('i18next-sync-fs-backend');

i18n
  .use(Backend)
  .init({
    initImmediate: false,
    lng: Config.locale,
    fallbackLng: "fi-FI",
    debug: true,
    ns: ["messages", "routes"],
    defaultNS: "messages",
    react: {
      wait: true
    },
    resources: locales
  });

export default i18n;
`

**Comment by jamuhl** [comment]
you will need to open this issue there: https://github.com/LegNeato/i18next-sync-fs-backend

this here is not the sync backend...sorry

**Comment by lenghia241** [comment]
opps sorry ab that :D

**Comment by jamuhl** [comment]
no problem...
