### ISSUE TITLE
Translation overrides

### ISSUE THREAD

**Issue by adamgajzlerowicz** [i18next/i18next-node-fs-backend#234]
My translations are currently placed in `*.json` files as per docs. I'd like to introduce translations inheritance and depending on `env` variable, use different translations files location, that I would provide in `loadPath` configuration object.

It would be easy if translations were stored `*.js` modules, I could extend a base module and override them. It is not possible with json though.

Is it possible at archieve this at all? Can you please recommend a solution? Thanks.

**Comment by jamuhl** [comment]
guess not with the fs-backend. But you can create a custom backend suiting your needs: https://www.i18next.com/misc/creating-own-plugins#backend

**Comment by adamgajzlerowicz** [comment]
Thank you for your answer. 
I gave it a thought and I decided to build a small script that will execute before next starts. It look for all base files, than for each one on those it will look for override and if it exists it will use Object.assign to override them.

Once translations are merged, they will be put in a location that next will be looking for them.

Thanks again

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
