### ISSUE TITLE
Feature: dev-mode, invalidate fs cache in dev-mode

### ISSUE THREAD

**Issue by felixmosh** [i18next/i18next-node-fs-backend#235]
Hi,

I'm working on SSR with node, and using this package, I've noticed that if I add new key / change an existing one, the SSR result it not changes.

I guess that it is related to `fs` cache.
Would it a good PR to make for invalidate require.cache if `NODE_ENV=development`?

**Comment by jamuhl** [comment]
It's a readfile not require -> https://github.com/i18next/i18next-node-fs-backend/blob/master/src/index.js#L34

i18next loads that once on init -> as server inits only once - there won't be a change until you restart the server

you can call i18next.reloadResources to trigger a reload: https://www.i18next.com/overview/api#reloadresources

**Comment by felixmosh** [comment]
Ha, got it, thanx for the explanation
