### ISSUE TITLE
Append missing keys to an existing file

### ISSUE THREAD

**Issue by pgom** [i18next/i18next-node-fs-backend#3]
I'm using i18next and therefore I'm trying to use i18next-node-fs-backend to save missing files. Besides that, I to integrate that in a template parser on gulp task. The issue I'm getting currently is that it only saves the last missing key because it uses `writeFile` function. 

@jamuhl could it make sense to use `appendFile` for this cases? Maybe controlled by a config?

**Comment by jamuhl** [comment]
appendFile just adds to the file end. wouldn't generate valid json.

isn't the issue that writeFile did not finished the write operation, so the next missing key just does not get the last change?

if so i might need to refactor this to queue the writes of missing keys.

**Comment by pgom** [comment]
@jamuhl in the meatime, I tried the `appendFile` and it does mess with result file as you said. The main problem is related with using this on top of glob of files. For each file, the function is called looking only for missing keys on that file and then writes it to the missing file. But only missing keys for the last file will remain because it will be the last invocation.

**Comment by jamuhl** [comment]
hm...sounds like a combination of the write issue (write not finished before next missing) and eventual running in parallel - not sure but gulp might run all files in parallel.

does the task run against on instance of i18next or do you create multiple instances? if one instance changing the fs backend to queue writes should solve the issue...might optimize that to debounce the write...

if parallel i'm not sure...you might need to override the missingKeyHandler on init (http://i18next.com/docs/options/) and queue that to some singleton store (in mem) then write the json.

**Comment by pgom** [comment]
Currently, it's running against one instance. And yes, gulp run files in parallel and that's pretty much the issue. You think it's possible to work something on this? I can jump in and help if you want.

**Comment by jamuhl** [comment]
might get to it today or tomorrow

**Comment by pgom** [comment]
Thanks @jamuhl

**Comment by jamuhl** [comment]
try latest 0.0.6

**Comment by jamuhl** [comment]
can this be closed?

**Comment by pgom** [comment]
Yeps @jamuhl
