### ISSUE TITLE
Feature request: Synchronous support

### ISSUE THREAD

**Issue by arve0** [i18next/i18next-node-fs-backend#4]
Would synchronous read/write fit in i18next-node-fs-backend, or should a fork be maintained? 

I do not have complete oversight of the handling between i18next and the backend, but I've read [index.js](https://github.com/i18next/i18next-node-fs-backend/blob/master/src/index.js). And for the looks of it, [`write`](https://github.com/i18next/i18next-node-fs-backend/blob/master/src/index.js#L70) need to be refactored to something like

```js
if (options.sync) {
  resources = readFileSync(...)
  ...
  fs.writeFileSync(filename, JSON.stringify(resources, null, this.options.jsonIndent))
  ...
```

For [`read`](https://github.com/i18next/i18next-node-fs-backend/blob/master/src/index.js#L50), I'm not sure how one would pass the resources back without the callback.

**Comment by jamuhl** [comment]
do the read, write as you say with `readFileSync` still use the callback to pass resources back.

i would prefer a own fork. eg. publish on npm 'i18next-node-fssync-backend'

**Comment by arve0** [comment]
https://www.npmjs.com/package/i18next-sync-fs-backend

**Comment by jamuhl** [comment]
great...added to i18next.com http://i18next.com/docs/ecosystem/#backends
