### ISSUE TITLE
document or fix interpolation behaviour

### ISSUE THREAD

**Issue by MartijnR** [i18next/i18next-node-fs-backend#51]
I got tripped up when I set the interpolation prefix and suffix of i18next to `__` during initialization since this is what my language resource files are using.

I eventually found out that this does not only apply to the `t()` function but also to how resources are loaded in this module. In other words I had to change:

```
loadPath: '/locales/{{lng}}/translation.json',
```

into:

```
loadPath: '/locales/__lng__/translation.json',
```

I think you could argue this is either a feature or a bug ;). I think, it would be better to keep interpolation for paths in this module, fixed to `{{lng}}` since paths and translation strings are such different animals.

**Comment by jamuhl** [comment]
it's a feature...not obvious but a feature ;)...will add some hints to readme.

**Comment by MartijnR** [comment]
Ok, thanks!
