### ISSUE TITLE
Add support for YAML files

### ISSUE THREAD

**Issue by manuelbieh** [i18next/i18next-node-fs-backend#72]
Hi,

I really like .yml files as "cleaner" alternative to json. Maybe you could consider adding support for .yml files, in addition to json and json5.

**Comment by jamuhl** [comment]
could consider accepting a PR...would accept a PR...;)

**Comment by manuelbieh** [comment]
https://github.com/i18next/i18next-node-fs-backend/pull/73

**Comment by jamuhl** [comment]
as merged
