### ISSUE TITLE
Question/Request to add missing keys in file located in the current language and the fallback language

### ISSUE THREAD

**Issue by TitaneBoy** [i18next/i18next-node-fs-backend#79]
Hi. Is there a way to add missing keys to files (when we specify options with tag addPath) in all languages ?

For example, if I specify in i18next option:

preload: ['fr', 'en-US'], fallbackLng:'en-US', saveMissingTo:'All', saveMissing:true, backend:{loadPath: 'language/static/{{lng}}/{{ns}}.json', addPath: 'language/static/{{lng}}/{{ns}}.missing.json', jsonIndent: 2}

and I get a web page in the internet brower (which is in French language or has the Accept-Language header tag set to fr ), which contains a string which is not translated in no language, the file containing missing keys will get the missing key in the current language (language/static/**fr**/{{ns}}.missing.json), but in the fallback language (in our current example, en-US), the missing key file will not be in the english missing key  file (language/static/**en-US**/{{ns}}.missing.json).

Is it possible to add the missing key in the current language missing.json file and the fallback language missing.json file if the missing key is not available in all .json file containing all the translated strings ?

Thank you for your answer.

**Comment by jamuhl** [comment]
might be `saveMissingTo: 'all'` non uppercase first char: http://i18next.com/docs/options/#init-options

**Comment by TitaneBoy** [comment]
Hi jamuhl..Thank you for your answer.

But I've already tried to put `'all'` instead of 'All' to the `saveMissingTo `option, but it does nothing: no missing key file is created when we put `'all'` to this option. We must put `'All' `instead to see this file created. But the main problem (My first comment) is still present.

**Comment by jamuhl** [comment]
what is you configuration on clientside?

**Comment by jamuhl** [comment]
ok i think i found an issue...give me a second

**Comment by TitaneBoy** [comment]
Well..For now, I'm testing my things only by server side.

Maybe I don't understand very well what do you mean by "client-side".

I don't know if this what you want to know, but i'm using Chrome, with French, English (US) and English as prefered languages.

**Comment by jamuhl** [comment]
can you try with v0.1.1

**Comment by TitaneBoy** [comment]
I have another weird issue (I think):

With this server side configuration:

var i18next = require('i18next');
var i18nextMiddleware = require('i18next-express-middleware')
var i18nextBackend = require('i18next-node-fs-backend');
var i18nextOptions = {debug:true, preload: ['es','fr', 'en-US'], load:'languageOnly', saveMissingTo:'all', saveMissing:true, ns:'Web_Server', defaultNS:'Web_Server', backend:{loadPath: 'language/static/{{lng}}/{{ns}}.json', addPath: 'language/static/{{lng}}/{{ns}}.missing.json', jsonIndent: 2}}

When I start my server, I can see in the console log that i18next is trying to load json file under 'dev' and 'en' folder languages (which gives me errono: -4058, code: 'ENOENT'...) and it only load fr and es .json files, but not en-US json file.

If I set the option `fallbackLng:'en-US',`,  it will load en-US, es and fr json files (which contains translated string of course), but it will try to load `'en'` json file, which is not specified in my options, and gives me the same error (-4058 ... )

Must I open a new issue for that ?

Thank you again for your kick answer..:-)

**Comment by TitaneBoy** [comment]
Ok...I will try now with your new version..

**Comment by TitaneBoy** [comment]
Hi again..
With your new version v0.1.1, with this server-side configuration:

var i18nextOptions = {debug:true, preload: ['es','fr', 'en-US'], load:'languageOnly', fallbackLng:'en-US', saveMissingTo:'all', saveMissing:true, ns:'Web_Server', defaultNS:'Web_Server', backend:{loadPath: 'language/static/{{lng}}/{{ns}}.json', addPath: 'language/static/{{lng}}/{{ns}}.missing.json', jsonIndent: 2}}

I triedto print a string which is no translated in 'en-US', 'fr' and 'es' and the missing key appears in the .missing.json file in the en-US folder, but not in the 'fr' folder. In my comprehension (correct me if I'm wrong), the missing key should appears in missing json file under the current language (for me, it's in french (fr)) and, if specified, in the fallback language (en-US).

And I tried now to remove the `load` option (so by default it is set to `'all'`) and no missing.json file at all is created for missing keys. :-(

**Comment by TitaneBoy** [comment]
Hi... with v0.1.1,  if `saveMissingTo` option is set to `'All'` (with first letter in big capital), it will create missing.json file only in the `'fr'` subfolder (language/static/fr/Web_Server.missing.json). If it is set to `'all'` (with no first letter in big capital), the missing.json file will be created only in the `'en-US'` subfolder (language/static/en-US/Web_Server.missing.json)

**Comment by jamuhl** [comment]
will need to test this again....will come back to this asap

**Comment by jamuhl** [comment]
can you try v0.1.2...found the issue and should be fixed now

**Comment by TitaneBoy** [comment]
Hello jamuhl.

With v0.1.2, it works perfectly. 

Thank you very much for your help and aswer :-)
