### ISSUE TITLE
i18next tries to load dev and en language resources 

### ISSUE THREAD

**Issue by TitaneBoy** [i18next/i18next-node-fs-backend#80]
Hi. This is my issue:

With this server side configuration:

```
var i18next = require('i18next');
var i18nextMiddleware = require('i18next-express-middleware')
var i18nextBackend = require('i18next-node-fs-backend');
var i18nextOptions = {debug:true, preload: ['es','fr', 'en-US'], saveMissingTo:'all', saveMissing:true, ns:'Web_Server', defaultNS:'Web_Server', backend:{loadPath: 'language/static/{{lng}}/{{ns}}.json', addPath: 'language/static/{{lng}}/{{ns}}.missing.json', jsonIndent: 2}}

i18next
  .use(i18nextMiddleware.LanguageDetector)
  .use(i18nextBackend)
  .init(i18nextOptions);

...
```

When I start my server, I can see in the console log that i18next is trying to load json resource file under '**dev**' and '**en**' folder languages (which gives me errono: -4058, code: 'ENOENT'...)

If I set the option **fallbackLng:'en-US'**, it will show in the console log that it loads en-US, es and fr json resources files but it will keep trying to load '**en**' json resource file too, which is not specified in my options, and which will give me the same error (-4058 ... ), but only for '**en**' language

These are the errors I get in the console (with NO  **fallbackLng** option set):

```
i18next::backendConnector: loading namespace Web_Server for language dev failed { [Error: ENOENT: no such file or directory, open 'C:\Personal_Data\
Project_Setup\Node.js\Express\MyDemoApp\language\static\dev\Resources_Web_Server.json']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Personal_Data\\Project_Setup\\Node.js\\Express\\MyDemoApp\\language\\static\\dev\\Resources_Web_Server.json' }
i18next::backendConnector: loading namespace Web_Server for language en failed { [Error: ENOENT: no such file or directory, open 'C:\Personal_Data\
Project_Setup\Node.js\Express\MyDemoApp\language\static\en\Resources_Web_Server.json']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Personal_Data\\Project_Setup\\Node.js\\Express\\MyDemoApp\\language\\static\\en\\Resources_Web_Server.json' }
```

This is what I observed. These errors will not stop the code to work (I think) but it creates unnecessary noise trace in the console log.

Thank you :-)

**Comment by jamuhl** [comment]
i18next always tries to lookup keys like this:
1) in language plus region, eg. en-US
2) if not found there try language only, eg en
3) still not found try in one of the fallback languages ( default dev )

you can change this by setting whitelist and load option on init and setting fallback to false

**Comment by TitaneBoy** [comment]
Wonderfull...Thank you for you answer and your tips..:-)
